version: '2'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
    - '10.0.10.2:2181:2181'
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
    - '10.0.10.3:9092:9092'
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes