---
message: "hello, spring cloud -unknown"

service:
  message: Hello World

---
spring:
  profiles: local
  cloud:
    gateway:
      enabled: true
    kubernetes:
      ribbon.enabled: false

      
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    fetchRegistry=true        

ribbon:
  eureka:
    enabled: true

message: "hello, spring cloud -local"

---
spring:
  profiles: dock-local
  cloud:
    gateway:
      enabled: true
    kubernetes:
      ribbon.enabled: false
      
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 172.18.1.2
  client:
    fetchRegistry=true        

ribbon:
  eureka:
    enabled: true
    
message: "hello, spring cloud -dock-local"

---

spring:
  profiles: dev

message: "hello, spring cloud -dev"

---

spring:
  profiles: prd
  
  
message: "hello, spring cloud -prd"

