---
message: "hello, spring cloud lobby api -default"

---
spring:
  profiles: local
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/lobby
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true   
  
  
server:
  port: 9000


message: "hello, spring cloud lobby api -local"
---
spring:
  profiles: local2
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/lobby
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true 
  
server:
  port: 9100

message: "hello, spring cloud lobby api -local2"

---
spring:
  profiles: dock-local

message: "hello, spring cloud lobby api -dock-local"

---

spring:
  profiles: dev

message: "hello, spring cloud lobby api -dev"

---

spring:
  profiles: prd

message: "hello, spring cloud lobby api -prd"
